// Generated by the Supabase MCP `generate_typescript_types` tool for project
// qdfmvhjrcmeoxbattnsm. Regenerate after every migration.
//
// In sync with the live project as of 2026-08-10, covering BOTH parallel
// streams that landed here:
//
//   0017_worker_checkins  (version 20260808140249) — the 16:30 check-in.
//   0018_task_reviews     (version 20260808123135) — task_reviews plus
//                          open_task_review and resolve_task_review.
//   0019_task_reviews_hardening (20260808125233) — function/grant changes only.
//   0020_task_review_supersede  (20260808130731) — the tasks_supersede_review
//                          trigger and a task_reviews.status constraint widening.
//
// Note the file numbers do NOT match application order: task_reviews was applied
// ~90 minutes before worker_checkins, but worker_checkins reached main first and
// took 0017, so the task-review migrations were renumbered upward on merge. The
// live ledger keys on the timestamps above, not on these prefixes. The two
// streams are independent — 0017_worker_checkins deliberately never touches
// tasks.status.
//
// 0019 and 0020 add nothing to the generated type surface beyond what 0018
// already did: task_reviews' columns are unchanged, and `status` is typed
// `string` rather than a literal union, so widening its check constraint is
// invisible here.
//
// The byte-equality regeneration check has NOT been re-run since both streams
// merged. Worth doing once, on main, after this lands — but do not regenerate
// from a feature branch: the live project may carry migrations your branch does
// not, and the diff will look like corruption without being it.
//
// ── notifications (0023), applied and VERIFIED ─────────────────────────────
// The `notifications` block below was written by hand — the migration had not
// been applied yet, and generating against a project that lacks the table
// would have silently DELETED the block instead of adding it. 0023 is now
// applied (version 20260810105627), and the block has been diffed against a
// real `generate_typescript_types` run: byte-identical, FK Relationships
// included. It is not a transcription any more; it is confirmed.
//
// ── THE FILE IS STILL BEHIND THE LIVE PROJECT, DELIBERATELY ────────────────
// Regenerating here would ALSO pull in a parallel stream this branch does not
// carry — the exact trap the paragraph above warns about, now concrete:
//
//   task_photos (version 20260810074738) — a whole table, plus
//   tasks.completion_proof, from the branch that claimed the 0022 file number.
//   That is why this file's migration is 0023 and not 0022.
//
// So: do NOT regenerate from this branch. Regenerate on main once both streams
// have merged, which will add task_photos/completion_proof and leave the
// notifications block untouched.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      companies: {
        Row: {
          created_at: string
          id: string
          language: string
          name: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          subscription_status: string
          trial_ends_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          language?: string
          name: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          subscription_status?: string
          trial_ends_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          language?: string
          name?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          subscription_status?: string
          trial_ends_at?: string
        }
        Relationships: []
      }
      conversation_summaries: {
        Row: {
          conversation_id: string
          covers_until_message_id: string
          created_at: string
          id: string
          summary: string
        }
        Insert: {
          conversation_id: string
          covers_until_message_id: string
          created_at?: string
          id?: string
          summary: string
        }
        Update: {
          conversation_id?: string
          covers_until_message_id?: string
          created_at?: string
          id?: string
          summary?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversation_summaries_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversation_summaries_covers_until_message_id_fkey"
            columns: ["covers_until_message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
        ]
      }
      conversations: {
        Row: {
          company_id: string
          created_at: string
          id: string
        }
        Insert: {
          company_id: string
          created_at?: string
          id?: string
        }
        Update: {
          company_id?: string
          created_at?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversations_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      dispatch_log: {
        Row: {
          channel: string
          dispatch_date: string
          id: string
          provider_message_id: string | null
          sent_at: string
          task_ids: Json
          worker_id: string
        }
        Insert: {
          channel?: string
          dispatch_date: string
          id?: string
          provider_message_id?: string | null
          sent_at?: string
          task_ids?: Json
          worker_id: string
        }
        Update: {
          channel?: string
          dispatch_date?: string
          id?: string
          provider_message_id?: string | null
          sent_at?: string
          task_ids?: Json
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "dispatch_log_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "dispatch_log_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      jobs: {
        Row: {
          address: string | null
          client_name: string | null
          company_id: string
          created_at: string
          ends_on: string | null
          id: string
          name: string
          starts_on: string | null
          status: string
        }
        Insert: {
          address?: string | null
          client_name?: string | null
          company_id: string
          created_at?: string
          ends_on?: string | null
          id?: string
          name: string
          starts_on?: string | null
          status?: string
        }
        Update: {
          address?: string | null
          client_name?: string | null
          company_id?: string
          created_at?: string
          ends_on?: string | null
          id?: string
          name?: string
          starts_on?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "jobs_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      knowledge_chunks: {
        Row: {
          chunk_index: number
          content: string
          document_id: string
          embedding: string
          heading_path: string
          id: string
          metadata: Json
          tsv: unknown
        }
        Insert: {
          chunk_index: number
          content: string
          document_id: string
          embedding: string
          heading_path?: string
          id?: string
          metadata?: Json
          tsv?: unknown
        }
        Update: {
          chunk_index?: number
          content?: string
          document_id?: string
          embedding?: string
          heading_path?: string
          id?: string
          metadata?: Json
          tsv?: unknown
        }
        Relationships: [
          {
            foreignKeyName: "knowledge_chunks_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "knowledge_documents"
            referencedColumns: ["id"]
          },
        ]
      }
      knowledge_documents: {
        Row: {
          category: string
          created_at: string
          id: string
          published_at: string | null
          source_ref: string
          source_type: string
          title: string
        }
        Insert: {
          category: string
          created_at?: string
          id?: string
          published_at?: string | null
          source_ref: string
          source_type: string
          title: string
        }
        Update: {
          category?: string
          created_at?: string
          id?: string
          published_at?: string | null
          source_ref?: string
          source_type?: string
          title?: string
        }
        Relationships: []
      }
      memories: {
        Row: {
          active: boolean
          company_id: string
          content: string
          created_at: string
          id: string
          kind: string
          subject_id: string | null
          subject_type: string | null
          updated_at: string
        }
        Insert: {
          active?: boolean
          company_id: string
          content: string
          created_at?: string
          id?: string
          kind: string
          subject_id?: string | null
          subject_type?: string | null
          updated_at?: string
        }
        Update: {
          active?: boolean
          company_id?: string
          content?: string
          created_at?: string
          id?: string
          kind?: string
          subject_id?: string | null
          subject_type?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "memories_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          channel: string
          content: Json
          content_format: string
          conversation_id: string
          created_at: string
          id: string
          role: string
        }
        Insert: {
          channel?: string
          content: Json
          content_format?: string
          conversation_id: string
          created_at?: string
          id?: string
          role: string
        }
        Update: {
          channel?: string
          content?: Json
          content_format?: string
          conversation_id?: string
          created_at?: string
          id?: string
          role?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_log: {
        Row: {
          audience: string
          channel: string
          company_id: string
          created_at: string
          error: string | null
          id: string
          kind: string
          notification_date: string
          profile_id: string | null
          provider_message_id: string | null
          status: string
          task_ids: Json
          worker_id: string | null
        }
        Insert: {
          audience: string
          channel?: string
          company_id: string
          created_at?: string
          error?: string | null
          id?: string
          kind: string
          notification_date: string
          profile_id?: string | null
          provider_message_id?: string | null
          status: string
          task_ids?: Json
          worker_id?: string | null
        }
        Update: {
          audience?: string
          channel?: string
          company_id?: string
          created_at?: string
          error?: string | null
          id?: string
          kind?: string
          notification_date?: string
          profile_id?: string | null
          provider_message_id?: string | null
          status?: string
          task_ids?: Json
          worker_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "notification_log_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notification_log_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notification_log_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "notification_log_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string | null
          company_id: string
          created_at: string
          id: string
          kind: string
          profile_id: string
          read_at: string | null
          subject_id: string | null
          subject_type: string | null
          title: string | null
        }
        Insert: {
          body?: string | null
          company_id: string
          created_at?: string
          id?: string
          kind: string
          profile_id: string
          read_at?: string | null
          subject_id?: string | null
          subject_type?: string | null
          title?: string | null
        }
        Update: {
          body?: string | null
          company_id?: string
          created_at?: string
          id?: string
          kind?: string
          profile_id?: string
          read_at?: string | null
          subject_id?: string | null
          subject_type?: string | null
          title?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "notifications_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          company_id: string
          created_at: string
          full_name: string
          id: string
          language: string
          phone: string
        }
        Insert: {
          company_id: string
          created_at?: string
          full_name: string
          id: string
          language?: string
          phone: string
        }
        Update: {
          company_id?: string
          created_at?: string
          full_name?: string
          id?: string
          language?: string
          phone?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      proposals: {
        Row: {
          action_args: Json
          action_name: string
          company_id: string
          conversation_id: string | null
          created_at: string
          id: string
          rendered_text: string
          resolved_at: string | null
          status: string
        }
        Insert: {
          action_args: Json
          action_name: string
          company_id: string
          conversation_id?: string | null
          created_at?: string
          id?: string
          rendered_text: string
          resolved_at?: string | null
          status?: string
        }
        Update: {
          action_args?: Json
          action_name?: string
          company_id?: string
          conversation_id?: string | null
          created_at?: string
          id?: string
          rendered_text?: string
          resolved_at?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "proposals_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "proposals_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      task_dependencies: {
        Row: {
          depends_on_task_id: string
          task_id: string
        }
        Insert: {
          depends_on_task_id: string
          task_id: string
        }
        Update: {
          depends_on_task_id?: string
          task_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "task_dependencies_depends_on_task_id_fkey"
            columns: ["depends_on_task_id"]
            isOneToOne: false
            referencedRelation: "dashboard_tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dependencies_depends_on_task_id_fkey"
            columns: ["depends_on_task_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["task_id"]
          },
          {
            foreignKeyName: "task_dependencies_depends_on_task_id_fkey"
            columns: ["depends_on_task_id"]
            isOneToOne: false
            referencedRelation: "task_board"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dependencies_depends_on_task_id_fkey"
            columns: ["depends_on_task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dependencies_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "dashboard_tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dependencies_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["task_id"]
          },
          {
            foreignKeyName: "task_dependencies_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "task_board"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dependencies_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
        ]
      }
      task_reviews: {
        Row: {
          company_id: string
          declared_at: string
          declared_by_worker_id: string | null
          id: string
          note: string | null
          resolved_at: string | null
          resolved_by: string | null
          status: string
          task_id: string
        }
        Insert: {
          company_id: string
          declared_at?: string
          declared_by_worker_id?: string | null
          id?: string
          note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string
          task_id: string
        }
        Update: {
          company_id?: string
          declared_at?: string
          declared_by_worker_id?: string | null
          id?: string
          note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string
          task_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "task_reviews_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_reviews_declared_by_worker_id_fkey"
            columns: ["declared_by_worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "task_reviews_declared_by_worker_id_fkey"
            columns: ["declared_by_worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_reviews_resolved_by_fkey"
            columns: ["resolved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_reviews_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "dashboard_tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_reviews_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["task_id"]
          },
          {
            foreignKeyName: "task_reviews_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "task_board"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_reviews_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
        ]
      }
      tasks: {
        Row: {
          assignee_worker_id: string | null
          company_id: string
          created_at: string
          description: string | null
          due_date: string | null
          duration_days: number | null
          id: string
          job_id: string | null
          materials: string[] | null
          source: string
          start_date: string | null
          status: string
          title: string
          updated_at: string
        }
        Insert: {
          assignee_worker_id?: string | null
          company_id: string
          created_at?: string
          description?: string | null
          due_date?: string | null
          duration_days?: number | null
          id?: string
          job_id?: string | null
          materials?: string[] | null
          source: string
          start_date?: string | null
          status?: string
          title: string
          updated_at?: string
        }
        Update: {
          assignee_worker_id?: string | null
          company_id?: string
          created_at?: string
          description?: string | null
          due_date?: string | null
          duration_days?: number | null
          id?: string
          job_id?: string | null
          materials?: string[] | null
          source?: string
          start_date?: string | null
          status?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "tasks_assignee_worker_id_fkey"
            columns: ["assignee_worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "tasks_assignee_worker_id_fkey"
            columns: ["assignee_worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "dashboard_obras"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      transcription_vocab: {
        Row: {
          company_id: string
          created_at: string
          id: string
          last_reinforced_at: string
          term: string
          weight: number
        }
        Insert: {
          company_id: string
          created_at?: string
          id?: string
          last_reinforced_at?: string
          term: string
          weight?: number
        }
        Update: {
          company_id?: string
          created_at?: string
          id?: string
          last_reinforced_at?: string
          term?: string
          weight?: number
        }
        Relationships: [
          {
            foreignKeyName: "transcription_vocab_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      translation_batches: {
        Row: {
          company_id: string
          created_at: string
          created_by: string | null
          done_count: number
          error: string | null
          expires_at: string
          finished_at: string | null
          from_locale: string
          id: string
          item_count: number
          origin: string
          reverted_at: string | null
          started_at: string | null
          status: string
          to_locale: string
        }
        Insert: {
          company_id: string
          created_at?: string
          created_by?: string | null
          done_count?: number
          error?: string | null
          expires_at?: string
          finished_at?: string | null
          from_locale: string
          id?: string
          item_count?: number
          origin: string
          reverted_at?: string | null
          started_at?: string | null
          status?: string
          to_locale: string
        }
        Update: {
          company_id?: string
          created_at?: string
          created_by?: string | null
          done_count?: number
          error?: string | null
          expires_at?: string
          finished_at?: string | null
          from_locale?: string
          id?: string
          item_count?: number
          origin?: string
          reverted_at?: string | null
          started_at?: string | null
          status?: string
          to_locale?: string
        }
        Relationships: [
          {
            foreignKeyName: "translation_batches_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "translation_batches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      translation_items: {
        Row: {
          applied_at: string | null
          batch_id: string
          column_name: string
          company_id: string
          created_at: string
          id: string
          new_value: Json | null
          old_value: Json
          row_id: string
          status: string
          table_name: string
        }
        Insert: {
          applied_at?: string | null
          batch_id: string
          column_name: string
          company_id: string
          created_at?: string
          id?: string
          new_value?: Json | null
          old_value: Json
          row_id: string
          status?: string
          table_name: string
        }
        Update: {
          applied_at?: string | null
          batch_id?: string
          column_name?: string
          company_id?: string
          created_at?: string
          id?: string
          new_value?: Json | null
          old_value?: Json
          row_id?: string
          status?: string
          table_name?: string
        }
        Relationships: [
          {
            foreignKeyName: "translation_items_batch_id_fkey"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "translation_batches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "translation_items_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_checkins: {
        Row: {
          answer: string
          answered_at: string
          checkin_date: string
          company_id: string
          created_at: string
          id: string
          inbound_message_id: string | null
          notification_id: string | null
          task_ids: Json
          worker_id: string
        }
        Insert: {
          answer: string
          answered_at?: string
          checkin_date: string
          company_id: string
          created_at?: string
          id?: string
          inbound_message_id?: string | null
          notification_id?: string | null
          task_ids?: Json
          worker_id: string
        }
        Update: {
          answer?: string
          answered_at?: string
          checkin_date?: string
          company_id?: string
          created_at?: string
          id?: string
          inbound_message_id?: string | null
          notification_id?: string | null
          task_ids?: Json
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_checkins_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_checkins_notification_id_fkey"
            columns: ["notification_id"]
            isOneToOne: false
            referencedRelation: "notification_log"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_checkins_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_checkins_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      workers: {
        Row: {
          active: boolean
          company_id: string
          created_at: string
          id: string
          language: string | null
          name: string
          phone: string | null
          trade: string | null
        }
        Insert: {
          active?: boolean
          company_id: string
          created_at?: string
          id?: string
          language?: string | null
          name: string
          phone?: string | null
          trade?: string | null
        }
        Update: {
          active?: boolean
          company_id?: string
          created_at?: string
          id?: string
          language?: string | null
          name?: string
          phone?: string | null
          trade?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "workers_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      dashboard_obras: {
        Row: {
          address: string | null
          company_id: string | null
          concluidas: number | null
          id: string | null
          name: string | null
          pendentes: number | null
          status: string | null
        }
        Relationships: [
          {
            foreignKeyName: "jobs_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      dashboard_tasks: {
        Row: {
          active_today: boolean | null
          active_tomorrow: boolean | null
          company_id: string | null
          days_overdue: number | null
          description: string | null
          due_date: string | null
          id: string | null
          job_id: string | null
          job_name: string | null
          job_status: string | null
          overdue: boolean | null
          start_date: string | null
          status: string | null
          title: string | null
          worker_name: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tasks_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "dashboard_obras"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      dispatch_tasks_today: {
        Row: {
          due_date: string | null
          job_address: string | null
          job_name: string | null
          start_date: string | null
          status: string | null
          task_description: string | null
          task_id: string | null
          task_title: string | null
          worker_id: string | null
          worker_name: string | null
          worker_phone: string | null
        }
        Relationships: []
      }
      task_board: {
        Row: {
          active_today: boolean | null
          active_tomorrow: boolean | null
          assignee_worker_id: string | null
          at_risk: boolean | null
          company_id: string | null
          created_at: string | null
          days_overdue: number | null
          depends_on_titles: string[] | null
          description: string | null
          due_date: string | null
          duration_days: number | null
          id: string | null
          is_open: boolean | null
          job_active: boolean | null
          job_id: string | null
          job_name: string | null
          job_status: string | null
          late_dependency_titles: string[] | null
          materials: string[] | null
          overdue: boolean | null
          risk_blocked: boolean | null
          risk_due_soon: boolean | null
          risk_late_dependency: boolean | null
          risk_late_start: boolean | null
          risk_paused_job: boolean | null
          start_date: string | null
          status: string | null
          title: string | null
          today: string | null
          updated_at: string | null
          window_end: string | null
          window_start: string | null
          worker_name: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tasks_assignee_worker_id_fkey"
            columns: ["assignee_worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "tasks_assignee_worker_id_fkey"
            columns: ["assignee_worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "dashboard_obras"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      complete_onboarding: {
        Args: {
          p_company_name: string
          p_full_name: string
          p_language?: string
          p_phone: string
        }
        Returns: string
      }
      finalize_proposal: {
        Args: { p_event: string; p_id: string; p_status: string }
        Returns: undefined
      }
      lisbon_hour: { Args: never; Returns: number }
      lisbon_today: { Args: never; Returns: string }
      open_task_review: {
        Args: { p_note?: string; p_task: string; p_worker?: string }
        Returns: string
      }
      resolve_task_review: {
        Args: { p_resolution: string; p_review: string }
        Returns: {
          out_job_id: string
          out_task_id: string
          out_task_status: string
        }[]
      }
      revert_translation_batch: { Args: { p_batch: string }; Returns: Json }
      search_knowledge: {
        Args: {
          filter_category?: string
          match_count?: number
          query_embedding: string
          query_text: string
        }
        Returns: {
          category: string
          chunk_id: string
          content: string
          document_title: string
          heading_path: string
          score: number
          source_ref: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
