// Generated by the Supabase MCP `generate_typescript_types` tool for project
// qdfmvhjrcmeoxbattnsm. Regenerate after every migration.
//
// In sync with the live project as of 2026-08-10, covering BOTH parallel
// streams that landed here:
//
//   0017_worker_checkins  (version 20260808140249) — the 16:30 check-in.
//   0018_task_reviews     (version 20260808123135) — task_reviews plus
//                          open_task_review and resolve_task_review.
//   0019_task_reviews_hardening (20260808125233) — function/grant changes only.
//   0020_task_review_supersede  (20260808130731) — the tasks_supersede_review
//                          trigger and a task_reviews.status constraint widening.
//
// Note the file numbers do NOT match application order: task_reviews was applied
// ~90 minutes before worker_checkins, but worker_checkins reached main first and
// took 0017, so the task-review migrations were renumbered upward on merge. The
// live ledger keys on the timestamps above, not on these prefixes. The two
// streams are independent — 0017_worker_checkins deliberately never touches
// tasks.status.
//
// 0019 and 0020 add nothing to the generated type surface beyond what 0018
// already did: task_reviews' columns are unchanged, and `status` is typed
// `string` rather than a literal union, so widening its check constraint is
// invisible here.
//
//   0023_task_photos (version 20260810074738) — task_photos, plus one new column,
//                          tasks.completion_proof. Applied to the live project
//                          from this branch after confirming its migration
//                          ledger was IDENTICAL to supabase/migrations/ (21
//                          entries, through revert_translation_batch_null_guard)
//                          — which is the precondition the warning below is
//                          about, not a blanket ban.
//
// Note what 0023 does NOT appear as. The bucket, the two storage.objects
// policies and every grant/RLS/CHECK are invisible here: this file types the
// `public` schema's shape only. `storage` is a different schema, and nothing
// about a column's WRITABILITY survives into TypeScript. task_photos'
// column-scoped INSERT grant is the load-bearing example — `source`,
// `worker_id` and `uploaded_by` are all typed as ordinary optional Insert
// fields, and tsc will happily let you write them. The database rejects it
// with 42501 at runtime. Do not read this file as a permission model.
//
// The byte-equality regeneration check has NOT been re-run since both streams
// merged. Worth doing once, on main, after this lands — but do not regenerate
// from a feature branch WITHOUT first checking `list_migrations` against
// supabase/migrations/: the live project may carry migrations your branch does
// not, and the diff will look like corruption without being it.
//
// ── notifications (0024), applied and VERIFIED ─────────────────────────────
// The `notifications` block below was written by hand, because the migration
// had not been applied yet and generating against a project that lacks the
// table would have silently DELETED the block instead of adding it. It is
// applied now (version 20260810105627) and the block has since been diffed
// against a real `generate_typescript_types` run: byte-identical, FK
// Relationships included. It is not a transcription any more; it is confirmed.
//
// ── whatsapp BSUID (0022) + opt-in (0025), BOTH APPLIED ────────────────────
// profiles/workers.whatsapp_user_id come from 0022_whatsapp_bsuid.sql, and
// .whatsapp_opt_in_at / .whatsapp_opt_out_at from 0025_whatsapp_optin.sql. All
// four were hand-added to this file ahead of time and are now backed by the
// live schema: 0022 was applied on 2026-08-11 (issue #28 needs to READ that
// column, and until then Stage 1's capture had been failing on every message
// with "column does not exist", swallowed by design and recording nothing).
//
// This file therefore no longer leads the live project in either direction, and
// a clean regeneration is possible again for the first time since 0022 was
// written. Both pairs were verified column-for-column against a real
// generate_typescript_types run at merge time; the byte-equality check on main
// is now unblocked.
//
// The capture still does its own isolated write rather than widening the
// profiles/workers SELECTs the webhook runs, and Stage 2's BSUID lookups are
// likewise separate queries. That is not obsolete now the migration is applied:
// it is what keeps sender resolution decoupled from schema-vs-deploy ordering
// in general — see AGENTS.md on code that reads ahead of a pending migration.
//
// Note the three columns sit adjacent and alphabetical — opt_in_at, opt_out_at,
// user_id — which is exactly where git put both sides of the merge conflict.
// They are unrelated features: consent (0025) and identity (0022).
//
// ── last_inbound_at (0030), HAND-ADDED AHEAD OF THE MIGRATION ──────────────
// profiles/workers.last_inbound_at comes from 0030_last_inbound_at.sql and is
// added here by hand, in alphabetical position, the same way 0022/0024/0025
// were. It is NOT yet confirmed against a real generate_typescript_types run —
// the migration may not be applied when you read this. Verify before relying on
// the byte-equality regeneration check.
//
// Reading ahead of the migration is safe here and only here, because the one
// consumer is deliberately defensive about it: readLastInboundAt() in
// apps/web/app/notifications/briefing.ts validates the value rather than
// trusting the type, and withinFreeFormWindow() treats anything unreadable —
// including the `undefined` a pre-migration select('*') returns — as "not in
// the window", i.e. send the paid template, i.e. exactly today's behaviour. The
// webhook's write side degrades to a swallowed 42703. Do not add a second,
// trusting reader of this column.
//
// ── worker agent (0027), WRITTEN BY HAND, NOT YET APPLIED ──────────────────
// `worker_conversations`, `worker_messages` and the single appended view column
// `task_board.job_address` come from 0027_worker_agent.sql, which is
// deliberately NOT applied to the live project — PRD 4 says applying is the
// maintainer's call. They are hand-written here for the same reason the
// `notifications` block once was: generating against a project that lacks the
// tables would silently DELETE these blocks rather than add them.
//
// Two consequences while the migration is unapplied, both of which the code is
// written to survive:
//   - any query against worker_conversations / worker_messages answers 42P01
//     ("relation does not exist"). The worker agent treats that like any other
//     storage failure: it logs and stays silent, which is the same outcome an
//     unknown sender already gets.
//   - task_board.job_address answers as `undefined` rather than erroring,
//     because every reader of that view uses select('*') (AGENTS.md). Do not
//     switch a task_board read to an explicit column list containing
//     job_address; that is the one edit that would turn a graceful degradation
//     into a 42703 on every worker turn.
//
// Regenerate this file after 0027 is applied and diff the three additions.
//
// ── ai_usage (0032), WRITTEN BY HAND, NOT YET APPLIED ──────────────────────
// The token ledger from 0032_ai_usage.sql (issue #53), added here in
// alphabetical position for the same reason `notifications` and the worker
// tables once were: generating against a project that lacks the table would
// silently DELETE this block rather than add it.
//
// One consequence while the migration is unapplied, and the code is written to
// survive it: every insert answers 42P01 ("relation does not exist"), which
// packages/core/src/agent/usage.ts swallows into a single `ai_usage.write_failed`
// warning line by design — recording a cost must never break a conversation.
// The operator cost page then reads an empty table and says so.
//
// Note what is INVISIBLE here, as always: nothing about writability survives
// into TypeScript. `usage_date` is typed as an ordinary optional Insert field
// and tsc will happily let you set it, but it is absent from the tenant's
// column-scoped INSERT grant and comes from lisbon_today(). Do not send one.
//
// ── checkin_photo_requests (0034), WRITTEN BY HAND, NOT YET APPLIED ────────
// The check-in photo request from 0034_checkin_photo_requests.sql (issue #52),
// added here in alphabetical position for the same reason as every block above
// it: generating against a project that lacks the table would silently DELETE
// it rather than add it.
//
// One consequence while the migration is unapplied, and the code is written to
// survive it: every query answers 42P01 ("relation does not exist"). Both
// callers — openPhotoRequest and readOpenPhotoRequest in
// apps/web/app/api/whatsapp/route.ts — swallow that into a log line, so the tap
// still files its claim and still acknowledges the worker, and the photo path
// simply falls through to the restricted worker agent exactly as it did before
// this feature existed. Nothing about the claim depends on this table.
//
// Invisible here as always: this table is deny-all under RLS with ZERO
// policies (notification_log's posture), and every grant is revoked from
// `authenticated`. tsc will let a tenant-scoped client select from it; the
// database returns nothing.
//
// ── task_assignees (0035), WRITTEN BY HAND, NOT YET APPLIED ────────────────
// The collaborator join table from 0035_task_collaborators.sql (issue #44),
// plus `set_task_collaborators` under Functions and the TWO APPENDED
// task_board columns `collaborator_worker_ids` / `collaborator_names`. Added
// here by hand for the same reason as every block above it: generating against
// a project that lacks the table would silently DELETE these rather than add
// them.
//
// Three consequences while the migration is unapplied, and the code is written
// to survive all three:
//   - any query against task_assignees answers 42P01 ("relation does not
//     exist"). Nothing reads it directly — the view carries the data — so the
//     only caller is the RLS matrix.
//   - `set_task_collaborators` answers 42883 ("function does not exist"). Both
//     callers (the agent's create_task/update_task and the /tarefas/[id] server
//     action) surface it as an ordinary write failure, so a manager is told the
//     change did not land instead of being told it did.
//   - the two view columns answer as `undefined`, because every task_board
//     reader uses select('*') (AGENTS.md). `readCollaborators` in
//     apps/web/app/notifications/briefing.ts validates rather than trusts, so a
//     deploy landing first briefs exactly the people it briefs today. Do NOT
//     switch a task_board read to an explicit column list naming either one.
//
// Invisible here as usual: the tenant grant on task_assignees is SELECT ONLY.
// The Insert/Update shapes below are typed because the generator always emits
// them, not because a tenant may use them — every write goes through the RPC.
//
// ── 0036 (issue #51), WRITTEN BY HAND, NOT YET APPLIED ─────────────────────
// company_schedules, cron_runs, `company_send_history` under Functions, and
// five APPENDED notification_log columns (delivered_at / read_at / failed_at /
// delivery_error_code / delivery_error). Added by hand for the same reason as
// every block above: regenerating against a project that lacks them would
// silently DELETE these rather than add them.
//
// Four consequences while the migration is unapplied, and every one of them is
// written to degrade rather than break:
//   - company_schedules answers 42P01. readCompanySchedules (apps/web/lib/
//     schedule.ts) catches that into a log line and returns an empty map, so
//     EVERY company falls back to the built-in 07:00 / 16:00 — byte-identical
//     to the product before this feature. This is the single most important
//     degradation in the change: the schedule is the send.
//   - cron_runs answers 42P01. recordCronRun swallows it, so a run is
//     unrecorded and nothing else changes; nothing reads it on a send path.
//   - company_send_history answers 42883 ("function does not exist"). The
//     /perfil/automacoes screen renders its history section empty with a note
//     rather than failing the page.
//   - the five notification_log columns are absent. They are NEVER in
//     claimNotification's INSERT — only in the webhook's UPDATE, inside a
//     catch — so a status callback is dropped and no send is affected. Do NOT
//     add any of them to that insert.
//
// Invisible here as usual: cron_runs is SELECT-only for tenants (the cron
// writes it on the service role), and company_schedules' tenant INSERT/UPDATE
// grants are COLUMN-SCOPED — `updated_at`/`updated_by` are stamped by triggers
// and refused to a client that names them.
//
// ── 0040 (issue #125), WRITTEN BY HAND, NOT YET APPLIED ────────────────────
// The conversation turn lock: three APPENDED nullable columns on
// `conversations` (turn_lock_token / turn_lock_expires_at / turn_queued_at)
// and three SECURITY DEFINER RPCs under Functions
// (claim/finish/renew_conversation_turn). Added by hand for the standing
// reason: regenerating against a project that lacks them would silently
// DELETE these rather than add them.
//
// Two consequences while the migration is unapplied, both survivable by
// construction:
//   - all three RPCs answer PGRST202 ("not in the schema cache") or 42883.
//     Their ONLY callers are the wrappers in
//     packages/core/src/agent/turn-lock.ts, every one of which catches that
//     into a log line and degrades: handleInbound runs UNLOCKED, which is
//     byte-for-byte the pre-0040 product. A missing migration costs
//     serialization for a while, never the chat.
//   - the three columns read as absent. Nothing selects them by name — no
//     code reads them at all; the RPCs are the only readers and writers.
//
// Invisible here as usual: 0040 REVOKES the tenant's UPDATE grant on
// `conversations` (the lock columns must be unforgeable at the grant layer,
// and no tenant code path ever updated the table), so the Update shape below
// is typed because the generator always emits one, not because a tenant may
// use it.
//
// ── 0042 (issue #120), WRITTEN BY HAND, NOT YET APPLIED ────────────────────
// problem_reports (the "something is broken" report, read only by the
// operator) and problem_report_requests (the WhatsApp "your next message is
// the report" staging row). Added by hand for the standing reason:
// regenerating against a project that lacks them would silently DELETE these
// rather than add them.
//
// Consequences while the migration is unapplied, all survivable by
// construction:
//   - both tables answer 42P01. The WhatsApp flow
//     (apps/web/lib/problem-report-flow.ts) catches every failure: a keyword
//     command is answered with the "could not register" apology rather than a
//     false "registered", and the armed-capture read simply reports "not
//     armed", so ordinary messages fall through to the agents exactly as
//     before the feature.
//   - the app form's insert fails and the page shows its error state — honest,
//     never a silent swallow, because a bug report Capo loses is the one
//     failure this feature exists to end.
//
// Invisible here as usual: problem_reports is INSERT-only for tenants with a
// COLUMN-SCOPED grant (company_id, profile_id, text, context — worker_id and
// channel are refused at the grant layer) and no SELECT at all; a tenant
// insert must never chain .select(), whose RETURNING needs the SELECT nobody
// holds. problem_report_requests is deny-all with every grant revoked.
//
// ── 0043 (issue #152), WRITTEN BY HAND, NOT YET APPLIED ────────────────────
// worker_requests — "diz ao chefe que preciso de mais tinta", filed by the
// fifth crew tool. Added by hand for the standing reason: regenerating against
// a project that lacks the table would silently DELETE this block rather than
// add it. Verify it column-for-column against a real
// generate_typescript_types run once 0043 is applied.
//
// Consequences while the migration is unapplied:
//   - the table answers 42P01. The tool catches it and answers the crew member
//     that it could not record the request, rather than a false "sent to the
//     manager"; the manager-side loader and the WhatsApp ping both fail soft
//     (home.requests_failed / request.ping_failed) and cost one card and one
//     line, never a page or a reply.
//   - notifications.kind still refuses 'worker_request', so even a row that
//     somehow landed would produce no inbox entry. Both halves arrive together.
//
// Invisible here as usual: worker_requests grants tenants SELECT and NOTHING
// else (no INSERT, no UPDATE, no DELETE — a manager must not be able to forge
// "a worker asked for this", nor rewrite what one wrote). Every write is the
// service role, which bypasses grants. tsc will happily let you build an
// Insert/Update object for it; the database answers 42501.

// ── 0044 (issue #154), WRITTEN BY HAND, NOT YET APPLIED ────────────────────
// material_checks — one daily "is it on site / is it missing" tick per
// material per obra, for the today horizon of the materials screen. Added by
// hand for the standing reason: regenerating against a project that lacks the
// table would silently DELETE this block rather than add it.
//
// One consequence while the migration is unapplied, and the code is written to
// survive it: every query answers 42P01 ("relation does not exist"). The read
// (loadMaterialChecks in apps/web/app/dashboard-data.ts) logs
// `materials.checks_read_failed` and answers an empty map, so today's list
// renders with nothing ticked — which is byte-identical to the product before
// this feature. The write (apps/web/app/(app)/obras/material-check-actions.ts)
// surfaces the failure to the manager rather than swallowing it, because a
// tick that silently did not land is the one outcome a check list must never
// produce.
//
// Invisible here as usual: the tenant's INSERT grant is COLUMN-SCOPED and
// excludes `check_date` (the day comes from the lisbon_today() default — a
// client that could name it could tick tomorrow), `checked_by` and
// `checked_at` (both stamped by triggers). The UPDATE grant reaches `status`
// ALONE. tsc will happily let you set any of them; the database answers 42501.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      ai_usage: {
        Row: {
          actor: string
          cache_read_tokens: number
          cache_write_tokens: number
          company_id: string
          created_at: string
          id: string
          input_tokens: number
          model_id: string
          model_role: string
          output_tokens: number
          profile_id: string | null
          provider: string
          surface: string
          usage_date: string
          worker_id: string | null
        }
        Insert: {
          actor: string
          cache_read_tokens?: number
          cache_write_tokens?: number
          company_id: string
          created_at?: string
          id?: string
          input_tokens?: number
          model_id: string
          model_role: string
          output_tokens?: number
          profile_id?: string | null
          provider: string
          surface: string
          usage_date?: string
          worker_id?: string | null
        }
        Update: {
          actor?: string
          cache_read_tokens?: number
          cache_write_tokens?: number
          company_id?: string
          created_at?: string
          id?: string
          input_tokens?: number
          model_id?: string
          model_role?: string
          output_tokens?: number
          profile_id?: string | null
          provider?: string
          surface?: string
          usage_date?: string
          worker_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ai_usage_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_usage_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_usage_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      // PENDING 0045 — hand-written, not generated. The throttle ledger behind
      // the account emails the app now sends itself through Resend
      // (apps/web/lib/auth-email.ts). Service-role only: RLS on, zero policies,
      // every grant revoked, so nothing on the tenant request path can read or
      // write it, and it has no foreign keys to describe. Regenerate this block
      // once 0045 is applied to the live project.
      auth_email_sends: {
        Row: {
          email_lower: string
          id: string
          kind: string
          sent_at: string
        }
        Insert: {
          email_lower: string
          id?: string
          kind: string
          sent_at?: string
        }
        Update: {
          email_lower?: string
          id?: string
          kind?: string
          sent_at?: string
        }
        Relationships: []
      }
      checkin_photo_requests: {
        Row: {
          checkin_date: string
          close_reason: string | null
          closed_at: string | null
          company_id: string
          created_at: string
          expires_at: string
          id: string
          next_index: number
          notification_id: string
          photos_received: number
          task_ids: Json
          worker_id: string
        }
        Insert: {
          checkin_date: string
          close_reason?: string | null
          closed_at?: string | null
          company_id: string
          created_at?: string
          expires_at: string
          id?: string
          next_index?: number
          notification_id: string
          photos_received?: number
          task_ids?: Json
          worker_id: string
        }
        Update: {
          checkin_date?: string
          close_reason?: string | null
          closed_at?: string | null
          company_id?: string
          created_at?: string
          expires_at?: string
          id?: string
          next_index?: number
          notification_id?: string
          photos_received?: number
          task_ids?: Json
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "checkin_photo_requests_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checkin_photo_requests_notification_id_fkey"
            columns: ["notification_id"]
            isOneToOne: false
            referencedRelation: "notification_log"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "checkin_photo_requests_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "checkin_photo_requests_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      companies: {
        Row: {
          created_at: string
          id: string
          language: string
          name: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          subscription_status: string
          trial_ends_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          language?: string
          name: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          subscription_status?: string
          trial_ends_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          language?: string
          name?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          subscription_status?: string
          trial_ends_at?: string
        }
        Relationships: []
      }
      company_schedules: {
        Row: {
          company_id: string
          created_at: string
          enabled: boolean
          id: string
          job_kind: string
          send_hour: number
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          company_id: string
          created_at?: string
          enabled?: boolean
          id?: string
          job_kind: string
          send_hour: number
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          company_id?: string
          created_at?: string
          enabled?: boolean
          id?: string
          job_kind?: string
          send_hour?: number
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "company_schedules_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "company_schedules_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      cron_runs: {
        Row: {
          company_id: string
          due_hour: number
          excluded_inactive: number
          excluded_no_consent: number
          excluded_unreachable: number
          failed: number
          finished_at: string | null
          id: string
          job_kind: string
          managers_no_consent: number
          messaged: number
          no_manager_account: boolean
          ran_at: string
          ran_hour: number
          run_date: string
          skipped_idle: number
        }
        Insert: {
          company_id: string
          due_hour: number
          excluded_inactive?: number
          excluded_no_consent?: number
          excluded_unreachable?: number
          failed?: number
          finished_at?: string | null
          id?: string
          job_kind: string
          managers_no_consent?: number
          messaged?: number
          no_manager_account?: boolean
          ran_at?: string
          ran_hour: number
          run_date: string
          skipped_idle?: number
        }
        Update: {
          company_id?: string
          due_hour?: number
          excluded_inactive?: number
          excluded_no_consent?: number
          excluded_unreachable?: number
          failed?: number
          finished_at?: string | null
          id?: string
          job_kind?: string
          managers_no_consent?: number
          messaged?: number
          no_manager_account?: boolean
          ran_at?: string
          ran_hour?: number
          run_date?: string
          skipped_idle?: number
        }
        Relationships: [
          {
            foreignKeyName: "cron_runs_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      conversation_summaries: {
        Row: {
          conversation_id: string
          covers_until_message_id: string
          created_at: string
          id: string
          summary: string
        }
        Insert: {
          conversation_id: string
          covers_until_message_id: string
          created_at?: string
          id?: string
          summary: string
        }
        Update: {
          conversation_id?: string
          covers_until_message_id?: string
          created_at?: string
          id?: string
          summary?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversation_summaries_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversation_summaries_covers_until_message_id_fkey"
            columns: ["covers_until_message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
        ]
      }
      conversations: {
        Row: {
          company_id: string
          created_at: string
          id: string
          turn_lock_expires_at: string | null
          turn_lock_token: string | null
          turn_queued_at: string | null
        }
        Insert: {
          company_id: string
          created_at?: string
          id?: string
          turn_lock_expires_at?: string | null
          turn_lock_token?: string | null
          turn_queued_at?: string | null
        }
        Update: {
          company_id?: string
          created_at?: string
          id?: string
          turn_lock_expires_at?: string | null
          turn_lock_token?: string | null
          turn_queued_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "conversations_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      dispatch_log: {
        Row: {
          channel: string
          dispatch_date: string
          id: string
          provider_message_id: string | null
          sent_at: string
          task_ids: Json
          worker_id: string
        }
        Insert: {
          channel?: string
          dispatch_date: string
          id?: string
          provider_message_id?: string | null
          sent_at?: string
          task_ids?: Json
          worker_id: string
        }
        Update: {
          channel?: string
          dispatch_date?: string
          id?: string
          provider_message_id?: string | null
          sent_at?: string
          task_ids?: Json
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "dispatch_log_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "dispatch_log_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      jobs: {
        Row: {
          address: string | null
          client_name: string | null
          company_id: string
          created_at: string
          ends_on: string | null
          id: string
          name: string
          starts_on: string | null
          status: string
        }
        Insert: {
          address?: string | null
          client_name?: string | null
          company_id: string
          created_at?: string
          ends_on?: string | null
          id?: string
          name: string
          starts_on?: string | null
          status?: string
        }
        Update: {
          address?: string | null
          client_name?: string | null
          company_id?: string
          created_at?: string
          ends_on?: string | null
          id?: string
          name?: string
          starts_on?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "jobs_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      knowledge_chunks: {
        Row: {
          chunk_index: number
          content: string
          document_id: string
          embedding: string
          heading_path: string
          id: string
          metadata: Json
          tsv: unknown
        }
        Insert: {
          chunk_index: number
          content: string
          document_id: string
          embedding: string
          heading_path?: string
          id?: string
          metadata?: Json
          tsv?: unknown
        }
        Update: {
          chunk_index?: number
          content?: string
          document_id?: string
          embedding?: string
          heading_path?: string
          id?: string
          metadata?: Json
          tsv?: unknown
        }
        Relationships: [
          {
            foreignKeyName: "knowledge_chunks_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "knowledge_documents"
            referencedColumns: ["id"]
          },
        ]
      }
      knowledge_documents: {
        Row: {
          category: string
          created_at: string
          id: string
          published_at: string | null
          source_ref: string
          source_type: string
          title: string
        }
        Insert: {
          category: string
          created_at?: string
          id?: string
          published_at?: string | null
          source_ref: string
          source_type: string
          title: string
        }
        Update: {
          category?: string
          created_at?: string
          id?: string
          published_at?: string | null
          source_ref?: string
          source_type?: string
          title?: string
        }
        Relationships: []
      }
      material_checks: {
        Row: {
          check_date: string
          checked_at: string
          checked_by: string | null
          company_id: string
          created_at: string
          id: string
          job_id: string | null
          material: string
          status: string
        }
        Insert: {
          check_date?: string
          checked_at?: string
          checked_by?: string | null
          company_id: string
          created_at?: string
          id?: string
          job_id?: string | null
          material: string
          status: string
        }
        Update: {
          check_date?: string
          checked_at?: string
          checked_by?: string | null
          company_id?: string
          created_at?: string
          id?: string
          job_id?: string | null
          material?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "material_checks_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "material_checks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "material_checks_checked_by_fkey"
            columns: ["checked_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      memories: {
        Row: {
          active: boolean
          company_id: string
          content: string
          created_at: string
          id: string
          kind: string
          profile_id: string | null
          subject_id: string | null
          subject_type: string | null
          updated_at: string
        }
        Insert: {
          active?: boolean
          company_id: string
          content: string
          created_at?: string
          id?: string
          kind: string
          profile_id?: string | null
          subject_id?: string | null
          subject_type?: string | null
          updated_at?: string
        }
        Update: {
          active?: boolean
          company_id?: string
          content?: string
          created_at?: string
          id?: string
          kind?: string
          profile_id?: string | null
          subject_id?: string | null
          subject_type?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "memories_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "memories_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      memory_consolidations: {
        Row: {
          company_id: string
          completed_at: string | null
          covers_until_at: string | null
          created_at: string
          error: string | null
          id: string
          memories_written: number
          messages_read: number
          run_date: string
          status: string
        }
        Insert: {
          company_id: string
          completed_at?: string | null
          covers_until_at?: string | null
          created_at?: string
          error?: string | null
          id?: string
          memories_written?: number
          messages_read?: number
          run_date: string
          status?: string
        }
        Update: {
          company_id?: string
          completed_at?: string | null
          covers_until_at?: string | null
          created_at?: string
          error?: string | null
          id?: string
          memories_written?: number
          messages_read?: number
          run_date?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "memory_consolidations_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          channel: string
          content: Json
          content_format: string
          conversation_id: string
          created_at: string
          id: string
          role: string
        }
        Insert: {
          channel?: string
          content: Json
          content_format?: string
          conversation_id: string
          created_at?: string
          id?: string
          role: string
        }
        Update: {
          channel?: string
          content?: Json
          content_format?: string
          conversation_id?: string
          created_at?: string
          id?: string
          role?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_log: {
        Row: {
          audience: string
          channel: string
          company_id: string
          created_at: string
          delivered_at: string | null
          delivery_error: string | null
          delivery_error_code: number | null
          error: string | null
          failed_at: string | null
          id: string
          kind: string
          notification_date: string
          profile_id: string | null
          provider_message_id: string | null
          read_at: string | null
          status: string
          task_ids: Json
          worker_id: string | null
        }
        Insert: {
          audience: string
          channel?: string
          company_id: string
          created_at?: string
          delivered_at?: string | null
          delivery_error?: string | null
          delivery_error_code?: number | null
          error?: string | null
          failed_at?: string | null
          id?: string
          kind: string
          notification_date: string
          profile_id?: string | null
          provider_message_id?: string | null
          read_at?: string | null
          status: string
          task_ids?: Json
          worker_id?: string | null
        }
        Update: {
          audience?: string
          channel?: string
          company_id?: string
          created_at?: string
          delivered_at?: string | null
          delivery_error?: string | null
          delivery_error_code?: number | null
          error?: string | null
          failed_at?: string | null
          id?: string
          kind?: string
          notification_date?: string
          profile_id?: string | null
          provider_message_id?: string | null
          read_at?: string | null
          status?: string
          task_ids?: Json
          worker_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "notification_log_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notification_log_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notification_log_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "notification_log_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string | null
          company_id: string
          created_at: string
          id: string
          kind: string
          profile_id: string
          push_attempts: number
          pushed_at: string | null
          read_at: string | null
          subject_id: string | null
          subject_type: string | null
          title: string | null
        }
        Insert: {
          body?: string | null
          company_id: string
          created_at?: string
          id?: string
          kind: string
          profile_id: string
          push_attempts?: number
          pushed_at?: string | null
          read_at?: string | null
          subject_id?: string | null
          subject_type?: string | null
          title?: string | null
        }
        Update: {
          body?: string | null
          company_id?: string
          created_at?: string
          id?: string
          kind?: string
          profile_id?: string
          push_attempts?: number
          pushed_at?: string | null
          read_at?: string | null
          subject_id?: string | null
          subject_type?: string | null
          title?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "notifications_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      problem_report_requests: {
        Row: {
          close_reason: string | null
          closed_at: string | null
          company_id: string
          created_at: string
          expires_at: string
          id: string
          profile_id: string | null
          worker_id: string | null
        }
        Insert: {
          close_reason?: string | null
          closed_at?: string | null
          company_id: string
          created_at?: string
          expires_at: string
          id?: string
          profile_id?: string | null
          worker_id?: string | null
        }
        Update: {
          close_reason?: string | null
          closed_at?: string | null
          company_id?: string
          created_at?: string
          expires_at?: string
          id?: string
          profile_id?: string | null
          worker_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "problem_report_requests_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "problem_report_requests_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "problem_report_requests_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "problem_report_requests_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      problem_reports: {
        Row: {
          channel: string
          company_id: string
          context: Json
          created_at: string
          id: string
          profile_id: string | null
          text: string
          worker_id: string | null
        }
        Insert: {
          channel?: string
          company_id: string
          context?: Json
          created_at?: string
          id?: string
          profile_id?: string | null
          text: string
          worker_id?: string | null
        }
        Update: {
          channel?: string
          company_id?: string
          context?: Json
          created_at?: string
          id?: string
          profile_id?: string | null
          text?: string
          worker_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "problem_reports_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "problem_reports_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "problem_reports_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "problem_reports_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          company_id: string
          confirm_posture: string
          created_at: string
          full_name: string
          id: string
          language: string
          last_inbound_at: string | null
          phone: string
          whatsapp_opt_in_at: string | null
          whatsapp_opt_out_at: string | null
          whatsapp_user_id: string | null
        }
        Insert: {
          company_id: string
          confirm_posture?: string
          created_at?: string
          full_name: string
          id: string
          language?: string
          last_inbound_at?: string | null
          phone: string
          whatsapp_opt_in_at?: string | null
          whatsapp_opt_out_at?: string | null
          whatsapp_user_id?: string | null
        }
        Update: {
          company_id?: string
          confirm_posture?: string
          created_at?: string
          full_name?: string
          id?: string
          language?: string
          last_inbound_at?: string | null
          phone?: string
          whatsapp_opt_in_at?: string | null
          whatsapp_opt_out_at?: string | null
          whatsapp_user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      proposals: {
        Row: {
          action_args: Json
          action_name: string
          company_id: string
          conversation_id: string | null
          created_at: string
          id: string
          rendered_text: string
          resolved_at: string | null
          status: string
        }
        Insert: {
          action_args: Json
          action_name: string
          company_id: string
          conversation_id?: string | null
          created_at?: string
          id?: string
          rendered_text: string
          resolved_at?: string | null
          status?: string
        }
        Update: {
          action_args?: Json
          action_name?: string
          company_id?: string
          conversation_id?: string | null
          created_at?: string
          id?: string
          rendered_text?: string
          resolved_at?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "proposals_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "proposals_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      // Hand-written ahead of migration 0026 being applied to the live project.
      // Regenerate from the database (supabase gen types) once it is applied.
      push_subscriptions: {
        Row: {
          auth: string
          company_id: string
          created_at: string
          endpoint: string
          id: string
          last_failed_at: string | null
          p256dh: string
          profile_id: string
          user_agent: string | null
        }
        Insert: {
          auth: string
          company_id: string
          created_at?: string
          endpoint: string
          id?: string
          last_failed_at?: string | null
          p256dh: string
          profile_id: string
          user_agent?: string | null
        }
        Update: {
          auth?: string
          company_id?: string
          created_at?: string
          endpoint?: string
          id?: string
          last_failed_at?: string | null
          p256dh?: string
          profile_id?: string
          user_agent?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "push_subscriptions_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "push_subscriptions_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      task_dependencies: {
        Row: {
          depends_on_task_id: string
          task_id: string
        }
        Insert: {
          depends_on_task_id: string
          task_id: string
        }
        Update: {
          depends_on_task_id?: string
          task_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "task_dependencies_depends_on_task_id_fkey"
            columns: ["depends_on_task_id"]
            isOneToOne: false
            referencedRelation: "dashboard_tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dependencies_depends_on_task_id_fkey"
            columns: ["depends_on_task_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["task_id"]
          },
          {
            foreignKeyName: "task_dependencies_depends_on_task_id_fkey"
            columns: ["depends_on_task_id"]
            isOneToOne: false
            referencedRelation: "task_board"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dependencies_depends_on_task_id_fkey"
            columns: ["depends_on_task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dependencies_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "dashboard_tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dependencies_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["task_id"]
          },
          {
            foreignKeyName: "task_dependencies_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "task_board"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_dependencies_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
        ]
      }
      task_assignees: {
        Row: {
          company_id: string
          created_at: string
          id: string
          role: string
          task_id: string
          worker_id: string
        }
        Insert: {
          company_id: string
          created_at?: string
          id?: string
          role?: string
          task_id: string
          worker_id: string
        }
        Update: {
          company_id?: string
          created_at?: string
          id?: string
          role?: string
          task_id?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "task_assignees_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_assignees_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "dashboard_tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_assignees_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["task_id"]
          },
          {
            foreignKeyName: "task_assignees_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "task_board"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_assignees_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_assignees_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "task_assignees_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      task_photos: {
        Row: {
          byte_size: number
          company_id: string
          created_at: string
          id: string
          mime: string
          source: string
          storage_path: string
          taken_at: string | null
          task_id: string
          uploaded_by: string | null
          worker_id: string | null
        }
        Insert: {
          byte_size: number
          company_id: string
          created_at?: string
          id?: string
          mime: string
          source?: string
          storage_path: string
          taken_at?: string | null
          task_id: string
          uploaded_by?: string | null
          worker_id?: string | null
        }
        Update: {
          byte_size?: number
          company_id?: string
          created_at?: string
          id?: string
          mime?: string
          source?: string
          storage_path?: string
          taken_at?: string | null
          task_id?: string
          uploaded_by?: string | null
          worker_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "task_photos_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_photos_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "dashboard_tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_photos_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["task_id"]
          },
          {
            foreignKeyName: "task_photos_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "task_board"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_photos_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_photos_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_photos_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "task_photos_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      task_reviews: {
        Row: {
          company_id: string
          declared_at: string
          declared_by_worker_id: string | null
          id: string
          note: string | null
          resolved_at: string | null
          resolved_by: string | null
          status: string
          task_id: string
        }
        Insert: {
          company_id: string
          declared_at?: string
          declared_by_worker_id?: string | null
          id?: string
          note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string
          task_id: string
        }
        Update: {
          company_id?: string
          declared_at?: string
          declared_by_worker_id?: string | null
          id?: string
          note?: string | null
          resolved_at?: string | null
          resolved_by?: string | null
          status?: string
          task_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "task_reviews_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_reviews_declared_by_worker_id_fkey"
            columns: ["declared_by_worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "task_reviews_declared_by_worker_id_fkey"
            columns: ["declared_by_worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_reviews_resolved_by_fkey"
            columns: ["resolved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_reviews_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "dashboard_tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_reviews_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["task_id"]
          },
          {
            foreignKeyName: "task_reviews_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "task_board"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "task_reviews_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
        ]
      }
      tasks: {
        Row: {
          assignee_worker_id: string | null
          company_id: string
          completion_proof: string | null
          created_at: string
          description: string | null
          due_date: string | null
          duration_days: number | null
          id: string
          job_id: string | null
          materials: string[] | null
          source: string
          start_date: string | null
          status: string
          title: string
          updated_at: string
        }
        Insert: {
          assignee_worker_id?: string | null
          company_id: string
          completion_proof?: string | null
          created_at?: string
          description?: string | null
          due_date?: string | null
          duration_days?: number | null
          id?: string
          job_id?: string | null
          materials?: string[] | null
          source: string
          start_date?: string | null
          status?: string
          title: string
          updated_at?: string
        }
        Update: {
          assignee_worker_id?: string | null
          company_id?: string
          completion_proof?: string | null
          created_at?: string
          description?: string | null
          due_date?: string | null
          duration_days?: number | null
          id?: string
          job_id?: string | null
          materials?: string[] | null
          source?: string
          start_date?: string | null
          status?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "tasks_assignee_worker_id_fkey"
            columns: ["assignee_worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "tasks_assignee_worker_id_fkey"
            columns: ["assignee_worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "dashboard_obras"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      transcription_vocab: {
        Row: {
          company_id: string
          created_at: string
          id: string
          last_reinforced_at: string
          term: string
          weight: number
        }
        Insert: {
          company_id: string
          created_at?: string
          id?: string
          last_reinforced_at?: string
          term: string
          weight?: number
        }
        Update: {
          company_id?: string
          created_at?: string
          id?: string
          last_reinforced_at?: string
          term?: string
          weight?: number
        }
        Relationships: [
          {
            foreignKeyName: "transcription_vocab_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      translation_batches: {
        Row: {
          company_id: string
          created_at: string
          created_by: string | null
          done_count: number
          error: string | null
          expires_at: string
          finished_at: string | null
          from_locale: string
          id: string
          item_count: number
          origin: string
          reverted_at: string | null
          started_at: string | null
          status: string
          to_locale: string
        }
        Insert: {
          company_id: string
          created_at?: string
          created_by?: string | null
          done_count?: number
          error?: string | null
          expires_at?: string
          finished_at?: string | null
          from_locale: string
          id?: string
          item_count?: number
          origin: string
          reverted_at?: string | null
          started_at?: string | null
          status?: string
          to_locale: string
        }
        Update: {
          company_id?: string
          created_at?: string
          created_by?: string | null
          done_count?: number
          error?: string | null
          expires_at?: string
          finished_at?: string | null
          from_locale?: string
          id?: string
          item_count?: number
          origin?: string
          reverted_at?: string | null
          started_at?: string | null
          status?: string
          to_locale?: string
        }
        Relationships: [
          {
            foreignKeyName: "translation_batches_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "translation_batches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      translation_items: {
        Row: {
          applied_at: string | null
          batch_id: string
          column_name: string
          company_id: string
          created_at: string
          id: string
          new_value: Json | null
          old_value: Json
          row_id: string
          status: string
          table_name: string
        }
        Insert: {
          applied_at?: string | null
          batch_id: string
          column_name: string
          company_id: string
          created_at?: string
          id?: string
          new_value?: Json | null
          old_value: Json
          row_id: string
          status?: string
          table_name: string
        }
        Update: {
          applied_at?: string | null
          batch_id?: string
          column_name?: string
          company_id?: string
          created_at?: string
          id?: string
          new_value?: Json | null
          old_value?: Json
          row_id?: string
          status?: string
          table_name?: string
        }
        Relationships: [
          {
            foreignKeyName: "translation_items_batch_id_fkey"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "translation_batches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "translation_items_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_checkins: {
        Row: {
          answer: string
          answered_at: string
          checkin_date: string
          company_id: string
          created_at: string
          id: string
          inbound_message_id: string | null
          notification_id: string | null
          task_ids: Json
          worker_id: string
        }
        Insert: {
          answer: string
          answered_at?: string
          checkin_date: string
          company_id: string
          created_at?: string
          id?: string
          inbound_message_id?: string | null
          notification_id?: string | null
          task_ids?: Json
          worker_id: string
        }
        Update: {
          answer?: string
          answered_at?: string
          checkin_date?: string
          company_id?: string
          created_at?: string
          id?: string
          inbound_message_id?: string | null
          notification_id?: string | null
          task_ids?: Json
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_checkins_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_checkins_notification_id_fkey"
            columns: ["notification_id"]
            isOneToOne: false
            referencedRelation: "notification_log"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_checkins_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_checkins_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_conversations: {
        Row: {
          company_id: string
          created_at: string
          id: string
          updated_at: string
          worker_id: string
        }
        Insert: {
          company_id: string
          created_at?: string
          id?: string
          updated_at?: string
          worker_id: string
        }
        Update: {
          company_id?: string
          created_at?: string
          id?: string
          updated_at?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_conversations_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_conversations_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: true
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "worker_conversations_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: true
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_messages: {
        Row: {
          channel: string
          checkin_id: string | null
          company_id: string
          content: Json
          content_format: string
          conversation_id: string
          created_at: string
          id: string
          photo_count: number
          role: string
          usage_date: string
        }
        Insert: {
          channel?: string
          checkin_id?: string | null
          company_id: string
          content: Json
          content_format?: string
          conversation_id: string
          created_at?: string
          id?: string
          photo_count?: number
          role: string
          usage_date?: string
        }
        Update: {
          channel?: string
          checkin_id?: string | null
          company_id?: string
          content?: Json
          content_format?: string
          conversation_id?: string
          created_at?: string
          id?: string
          photo_count?: number
          role?: string
          usage_date?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_messages_checkin_id_fkey"
            columns: ["checkin_id"]
            isOneToOne: false
            referencedRelation: "worker_checkins"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_messages_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "worker_conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_day_links: {
        Row: {
          company_id: string
          created_at: string
          expires_at: string
          last_opened_at: string | null
          link_date: string
          opened_count: number
          token: string
          worker_id: string
        }
        Insert: {
          company_id: string
          created_at?: string
          expires_at: string
          last_opened_at?: string | null
          link_date: string
          opened_count?: number
          token: string
          worker_id: string
        }
        Update: {
          company_id?: string
          created_at?: string
          expires_at?: string
          last_opened_at?: string | null
          link_date?: string
          opened_count?: number
          token?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_day_links_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_day_links_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      worker_requests: {
        Row: {
          category: string | null
          company_id: string
          created_at: string
          id: string
          manager_notified_at: string | null
          needed_by: string | null
          task_id: string | null
          text: string
          worker_id: string
        }
        Insert: {
          category?: string | null
          company_id: string
          created_at?: string
          id?: string
          manager_notified_at?: string | null
          needed_by?: string | null
          task_id?: string | null
          text: string
          worker_id: string
        }
        Update: {
          category?: string | null
          company_id?: string
          created_at?: string
          id?: string
          manager_notified_at?: string | null
          needed_by?: string | null
          task_id?: string | null
          text?: string
          worker_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "worker_requests_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_requests_task_id_fkey"
            columns: ["task_id"]
            isOneToOne: false
            referencedRelation: "tasks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "worker_requests_worker_id_fkey"
            columns: ["worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
        ]
      }
      workers: {
        Row: {
          active: boolean
          company_id: string
          created_at: string
          id: string
          language: string | null
          last_inbound_at: string | null
          name: string
          phone: string | null
          trade: string | null
          whatsapp_opt_in_at: string | null
          whatsapp_opt_out_at: string | null
          whatsapp_user_id: string | null
        }
        Insert: {
          active?: boolean
          company_id: string
          created_at?: string
          id?: string
          language?: string | null
          last_inbound_at?: string | null
          name: string
          phone?: string | null
          trade?: string | null
          whatsapp_opt_in_at?: string | null
          whatsapp_opt_out_at?: string | null
          whatsapp_user_id?: string | null
        }
        Update: {
          active?: boolean
          company_id?: string
          created_at?: string
          id?: string
          language?: string | null
          last_inbound_at?: string | null
          name?: string
          phone?: string | null
          trade?: string | null
          whatsapp_opt_in_at?: string | null
          whatsapp_opt_out_at?: string | null
          whatsapp_user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "workers_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      dashboard_obras: {
        Row: {
          address: string | null
          company_id: string | null
          concluidas: number | null
          id: string | null
          name: string | null
          pendentes: number | null
          status: string | null
        }
        Relationships: [
          {
            foreignKeyName: "jobs_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      dashboard_tasks: {
        Row: {
          active_today: boolean | null
          active_tomorrow: boolean | null
          company_id: string | null
          days_overdue: number | null
          description: string | null
          due_date: string | null
          id: string | null
          job_id: string | null
          job_name: string | null
          job_status: string | null
          overdue: boolean | null
          start_date: string | null
          status: string | null
          title: string | null
          worker_name: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tasks_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "dashboard_obras"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      dispatch_tasks_today: {
        Row: {
          due_date: string | null
          job_address: string | null
          job_name: string | null
          start_date: string | null
          status: string | null
          task_description: string | null
          task_id: string | null
          task_title: string | null
          worker_id: string | null
          worker_name: string | null
          worker_phone: string | null
        }
        Relationships: []
      }
      task_board: {
        Row: {
          active_today: boolean | null
          active_tomorrow: boolean | null
          assignee_worker_id: string | null
          at_risk: boolean | null
          collaborator_names: string[] | null
          collaborator_worker_ids: string[] | null
          company_id: string | null
          created_at: string | null
          days_overdue: number | null
          depends_on_titles: string[] | null
          description: string | null
          due_date: string | null
          duration_days: number | null
          id: string | null
          is_open: boolean | null
          job_active: boolean | null
          job_address: string | null
          job_id: string | null
          job_name: string | null
          job_status: string | null
          late_dependency_titles: string[] | null
          materials: string[] | null
          overdue: boolean | null
          risk_blocked: boolean | null
          risk_due_soon: boolean | null
          risk_late_dependency: boolean | null
          risk_late_start: boolean | null
          risk_paused_job: boolean | null
          start_date: string | null
          status: string | null
          title: string | null
          today: string | null
          updated_at: string | null
          window_end: string | null
          window_start: string | null
          worker_name: string | null
        }
        Relationships: [
          {
            foreignKeyName: "tasks_assignee_worker_id_fkey"
            columns: ["assignee_worker_id"]
            isOneToOne: false
            referencedRelation: "dispatch_tasks_today"
            referencedColumns: ["worker_id"]
          },
          {
            foreignKeyName: "tasks_assignee_worker_id_fkey"
            columns: ["assignee_worker_id"]
            isOneToOne: false
            referencedRelation: "workers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "dashboard_obras"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "tasks_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Functions: {
      complete_onboarding: {
        Args: {
          p_company_name: string
          p_full_name: string
          p_language?: string
          p_phone: string
        }
        Returns: string
      }
      finalize_proposal: {
        Args: { p_event: string; p_id: string; p_status: string }
        Returns: undefined
      }
      note_day_link_opened: { Args: { p_token: string }; Returns: undefined }
      lisbon_hour: { Args: never; Returns: number }
      lisbon_today: { Args: never; Returns: string }
      open_task_review: {
        Args: { p_note?: string; p_task: string; p_worker?: string }
        Returns: string
      }
      resolve_task_review: {
        Args: { p_resolution: string; p_review: string }
        Returns: {
          out_job_id: string
          out_task_id: string
          out_task_status: string
        }[]
      }
      revert_translation_batch: { Args: { p_batch: string }; Returns: Json }
      // 0035 (issue #44). Replaces the WHOLE collaborator set for one task and
      // returns how many rows the task ends up carrying. The lead is never in
      // it — pass only the helpers; `tasks.assignee_worker_id` stays the lead
      // and stays the only way to change one.
      set_task_collaborators: {
        Args: { p_task: string; p_workers: string[] }
        Returns: number
      }
      // 0036 (issue #51). The ONLY window a tenant gets into notification_log,
      // which keeps its deny-all posture (RLS on, zero policies). SECURITY
      // DEFINER, so its auth.uid()/company check is the entire boundary — see
      // the migration, and scripts/rls-isolation-matrix.mjs, which attacks it.
      company_send_history: {
        Args: { p_from: string; p_to: string }
        Returns: {
          id: string
          kind: string
          audience: string
          worker_id: string | null
          profile_id: string | null
          notification_date: string
          status: string
          task_count: number
          provider_message_id: string | null
          error: string | null
          created_at: string
          delivered_at: string | null
          read_at: string | null
          failed_at: string | null
          delivery_error_code: number | null
          delivery_error: string | null
        }[]
      }
      // 0033. A marker, not a computation: the welcome sweep asks for it before
      // it sends anything, and a missing function means the once-ever index and
      // the backfill are not in place yet, so nothing goes out.
      welcome_ledger_ready: { Args: never; Returns: boolean }
      search_knowledge: {
        Args: {
          filter_category?: string
          match_count?: number
          query_embedding: string
          query_text: string
        }
        Returns: {
          category: string
          chunk_id: string
          content: string
          document_title: string
          heading_path: string
          score: number
          source_ref: string
        }[]
      }
      // 0040 (issue #125). The turn lock: SECURITY DEFINER, called only from
      // packages/core/src/agent/turn-lock.ts, whose wrappers degrade to an
      // unlocked turn when any of the three is missing — see the header note.
      claim_conversation_turn: {
        Args: { p_conversation: string; p_token: string; p_ttl_seconds?: number }
        Returns: string
      }
      finish_conversation_turn: {
        Args: { p_conversation: string; p_token: string; p_force?: boolean }
        Returns: string
      }
      renew_conversation_turn: {
        Args: { p_conversation: string; p_token: string; p_ttl_seconds?: number }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
