import type { z } from 'zod';
import type { Db } from '@capo/db/client';
import type { Locale } from '@capo/i18n/locale';
import type { TaskPhotoMime } from '../../media/photos';

// The worker agent's tool contract — a SECOND, deliberately incompatible type
// system sitting beside ../types.ts.
//
// Read the two side by side once and the design is obvious: `WorkerContext` and
// `ToolContext` are MUTUALLY UNASSIGNABLE. Each requires fields the other does
// not have, so neither is a subtype of the other, so a `CapoTool` cannot be put
// in `workerRoster` and a `WorkerTool` cannot be put in `roster`. That is the
// isolation — a type error, produced by `tsc --noEmit` on every package in CI,
// not a review comment somebody has to remember to write.
//
// This is the first place in this codebase where UNTRUSTED TEXT reaches a
// model. A worker's phone can write any sentence at all, including a very good
// impression of the manager giving an order, and there is no auth.uid() on this
// path so RLS backstops nothing. Every safety property here therefore has to be
// something the compiler or the database enforces. Prefer a compile error over
// a runtime check, and a runtime check over a sentence in a prompt.

/**
 * One photo that arrived with the inbound message, already downloaded from
 * Meta's CDN and held in memory for the duration of this turn.
 *
 * NOT yet in Storage, and that ordering is forced by the schema rather than
 * chosen: a task photo's object key is `{company_id}/{task_id}/{uuid}.{ext}`
 * (media/photos.ts), the storage.objects policies read segment 1 as the tenant
 * and the `task_photos_path_scoped` CHECK re-derives the whole thing — so the
 * bytes cannot be written anywhere legitimate until the TASK is known, and the
 * task is only known once `declare_task_done` names it. Hop 1's media URL lasts
 * ~5 minutes and is effectively single-use, so the download cannot be deferred
 * either. Downloaded now, written when a task claims them.
 *
 * `id` is the ONLY member the model ever sees. It is a per-turn handle, not a
 * database id, and it is generated by the route rather than taken from Meta's
 * media id so that nothing the model emits can be replayed against the Graph
 * API. The model has no fetch capability, so photos it did not receive do not
 * exist as far as it is concerned.
 */
export interface PendingPhoto {
  id: string;
  mime: TaskPhotoMime;
  bytes: Uint8Array;
  byteSize: number;
}

/**
 * Everything a worker tool is allowed to know.
 *
 * Compare `ToolContext` (../types.ts): it carries `userId`, `actor`,
 * `recentUserTexts` and `locales`. NONE of them appear here, and each absence
 * closes a specific door:
 *
 *   recentUserTexts — the guard's entire evidence pool (guard.ts:26-37). There
 *     is no manager in this loop, so "the manager told me to" is not a claim
 *     that can be made, checked, or forged. `WorkerTool` correspondingly has no
 *     `guarded` field AT ALL, rather than a `guarded?: never` — the concept is
 *     absent, not disabled.
 *   userId — profiles.id. `set_language` (language.ts:39) needs it to write one
 *     manager's dial; a worker has no profile and must not be able to write
 *     anyone's.
 *   actor — 'manager' | 'capo', recorded as tasks.source. A worker is neither.
 *   locales — the two-dial LocaleContext, one of whose dials is the COMPANY's
 *     stored-text language. A worker gets one locale: the language spoken to
 *     THEM. They cannot move what the company stores.
 *
 * The escalation path is closed by the type checker rather than by vigilance:
 * `createProposal` (propose.ts) takes a `ToolContext`, and no worker tool can
 * construct one. A worker therefore cannot manufacture an approval card for the
 * manager to tap.
 */
export interface WorkerContext {
  /**
   * ALWAYS the service-role client. There is no session on this path — the
   * WhatsApp webhook is a system caller and auth.uid() is null — so RLS
   * enforces NOTHING here. Every scoping filter below is doing work that RLS
   * does elsewhere; none of them is defence in depth.
   */
  db: Db;
  /** From workers.company_id, resolved by PHONE (or BSUID). Never from input. */
  companyId: string;
  /** From workers.id, resolved by PHONE (or BSUID). Never from input. */
  workerId: string;
  conversationId: string;
  /** workers.language ?? companies.language. One dial, theirs. */
  locale: Locale;
  /**
   * The ONLY task ids this turn may touch, computed BEFORE the model runs from
   * this worker's own open rows on `task_board`.
   *
   * Never widened by anything the model or the worker says. A guessed uuid —
   * including a real one belonging to a colleague in the same company — is
   * refused in-process, so it never reaches the database at all and cannot be
   * timed as an existence oracle.
   */
  scope: { taskIds: readonly string[] };
  /** The evening ask this reply belongs to; null for an unprompted message. */
  checkinId: string | null;
  /** Photos from THIS inbound message. See PendingPhoto. */
  pendingPhotos: readonly PendingPhoto[];
  /** Model turns this worker has left today. Informational inside the loop —
   *  the cap is enforced before the loop starts, where refusing costs nothing. */
  budget: number;
}

/**
 * The worker roster contract.
 *
 * `execute` is a FUNCTION-TYPED PROPERTY, not a method. That is not a style
 * choice: TypeScript checks method parameters BIVARIANTLY even under
 * `strictFunctionTypes`, and only a property gets the contravariant check that
 * makes a wrong context type an error. `CapoTool.execute` is a method, so the
 * incompatibility has to come from the context types themselves — which is why
 * they are mutually unassignable rather than merely different.
 *
 * `audience` is the belt to that braces. It is required here and absent from
 * `CapoTool`, so no manager tool can ever satisfy this interface no matter what
 * later happens to the two context shapes. It costs one line per tool and it
 * survives refactors that structural reasoning would not.
 *
 * There is NO `guarded` field. See WorkerContext above.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export interface WorkerTool<In = any, Out = any> {
  readonly audience: 'worker';
  name: string;
  description: string;
  inputSchema: z.ZodType<In>;
  execute: (input: In, ctx: WorkerContext) => Promise<Out>;
}

/**
 * What a worker tool returns when it refuses. Deliberately terse and
 * MACHINE-FACING: the model renders the refusal to the worker in their own
 * language, and a message that quoted an id back would turn a refusal into an
 * oracle about which ids exist.
 */
export interface WorkerToolError {
  status: 'error';
  message: string;
}

export function workerToolError(message: string): WorkerToolError {
  return { status: 'error', message };
}
